baseURL = 'https://turing1urkss.github.io/mypage/'
languageCode = 'en-us'
title = 'Leandro Llontop' # develeoper
theme = "hugo-noir"

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true # Recommended for clearer URLs like /en/blog, /es/blog

[languages]

  [languages.en]
    languageName = "English"
    title = "LeandroEN"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5

  [languages.es]
    languageName = "Español"
    title = "LeandroES"
    weight = 2
    contentDir = "content/es"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Sobre Mí"
        pageRef = "/about"
        weight = 1
      [[languages.es.menu.main]]
        name = "Experiencia"
        pageRef = "/experience"
        weight = 2
      [[languages.es.menu.main]]
        name = "Proyectos"
        pageRef = "/projects"
        weight = 3
      [[languages.es.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 4
      [[languages.es.menu.main]]
        name = "Contacto"
        pageRef = "/contact"
        weight = 5

  [languages.fr]
    languageName = "Français"
    title = "LeandroFR"
    weight = 3
    contentDir = "content/fr"
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "À Propos"
        pageRef = "/about"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expérience"
        pageRef = "/experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Projets"
        pageRef = "/projects"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 4
      [[languages.fr.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5

[params]
  name = "Leandro Llontop"
  location = "Nantes, France"
  description = "Description ..."
  profile_image = "/images/photo1.jpeg" # Place in your site's static/images/
  # Social links
  github = "https://github.com/tUrInG1uRKSS"
  twitter = "https://twitter.com/yourusername"
  linkedin = "https://www.linkedin.com/in/leandrollontopllh/"
  email = "m.leandro.ll.herrera@gmail.com"
  # ... other params ...
